name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Lấy mã nguồn từ repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Thiết lập Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3. Cài đặt các phụ thuộc
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest  # Cài đặt pytest
          pip install -r requirements.txt  # Cài đặt các phụ thuộc khác

      # 4. Chạy kiểm thử
      - name: Run tests
        run: |
          pytest test_payment.py
          # pytest test_vehicle.py
  
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build  # Chạy sau khi job build hoàn thành

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Deploy to Heroku
  #       env:
  #         HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  #         HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
  #       run: |
  #         git remote add heroku https://git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
  #         git push heroku main -f