name: CI Pipeline

on:
  push:
    branches:
      - main  # Kích hoạt khi push code vào nhánh chính
  pull_request:
    branches:
      - main  # Kích hoạt khi tạo pull request vào nhánh chính

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Lấy mã nguồn từ repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Thiết lập Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Chỉnh theo phiên bản Python mà bạn đang sử dụng

      # 3. Cài đặt các phụ thuộc
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Chạy kiểm thử
      - name: Run tests
        run: |
          pytest test_payment.py
          pytest test_vehicle.py
